# Generated by Django 4.2 on 2023-04-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=12)),
                ('DateDrive', models.DateField()),
            ],
        ),
    ]
